// Copyright 2026 Pride Leong.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "tianshu/compiler/codegen.h"

#include <algorithm>
#include <cstddef>
#include <sstream>
#include <string>
#include <vector>

#include "tianshu/compiler/ir.h"

namespace tianshu::compiler {
namespace {

// Wire-replay accessor per node kind; sources are driven by the run
// loop, never wired, so they have no entry here.
[[nodiscard]] const char* wire_accessor(const std::string& kind) {
  constexpr const char* kKinds[] = {"map", "join", "op", "stateful", "span", "from", "sink"};
  constexpr const char* kAccessors[] = {"maps",  "joins", "ops",  "statefuls",
                                        "spans", "froms", "sinks"};
  constexpr std::size_t kCount = sizeof(kKinds) / sizeof(kKinds[0]);
  for (std::size_t i = 0; i < kCount; ++i) {
    if (kind == kKinds[i]) {
      return kAccessors[i];
    }
  }
  return nullptr;
}

// Kinds that carry a specialize hook (ADR-0032); everything else
// (op/stateful/span/from) installs through the generic wire replay.
[[nodiscard]] bool has_specialize_hook(const std::string& kind) {
  return kind == "map" || kind == "join" || kind == "sink";
}

// Declaration indices of `kind`, ascending — the artifact installs in
// the same per-kind declaration order as FlowRuntime::wire(), so
// registration order (dispatcher notify order, consumer fan order)
// matches the interpreter exactly.
[[nodiscard]] std::vector<std::size_t> decl_indices_of(const IrGraph& graph, const char* kind) {
  std::vector<std::size_t> indices;
  for (const auto& node : graph.nodes()) {
    if (node.kind == kind) {
      indices.push_back(static_cast<std::size_t>(node.decl_index));
    }
  }
  std::ranges::sort(indices);
  return indices;
}

}  // namespace

std::string generate_source(const IrGraph& graph) {
  const std::string hash = graph.stable_hash();

  std::ostringstream out;
  out << "// Generated by the tianshu L1 pipeline (ADR-0030). Do not edit.\n";
  out << "// flow: " << graph.flow_name() << "  hash: " << hash << "\n";
  out << "// install: specialized per-message wiring (ADR-0032); the plan\n";
  out << "// (fast/generic channel classification, history capture) is derived\n";
  out << "// from the flow at begin_specialize() time.\n";
  out << "// topology (canonical order):\n";
  for (const auto& node : graph.nodes()) {
    out << "//   " << node.topo_order << "  " << node.kind;
    for (const auto& in : node.inputs) {
      out << " " << in;
    }
    if (!node.output.empty()) {
      out << " -> " << node.output;
    }
    out << "\n";
  }
  out << "\n" << R"(#include "tianshu/dsl/dsl_runtime.h")" << "\n\n";
  out << R"(extern "C" const char* tianshu_flow_hash() { return ")" << hash << R"("; })" << "\n\n";
  out << R"(extern "C" void tianshu_flow_install(tianshu::dsl::FlowRuntime* rt,)"
      << "\n";
  out << R"(                                     const tianshu::dsl::Flow* flow) {)"
      << "\n";
  out << "  tianshu::dsl::SpecializeBuilder plan = rt->begin_specialize(*flow);\n";
  constexpr const char* kInstallOrder[] = {"map", "join", "op", "stateful", "span", "from", "sink"};
  for (const char* kind : kInstallOrder) {
    const char* accessor = wire_accessor(kind);
    if (accessor == nullptr) {
      continue;
    }
    for (const std::size_t index : decl_indices_of(graph, kind)) {
      if (has_specialize_hook(kind)) {
        out << "  if (flow->" << accessor << "()[" << index << "].specialize) {\n";
        out << "    flow->" << accessor << "()[" << index << "].specialize(*rt, plan);\n";
        out << "  } else {\n";
        out << "    flow->" << accessor << "()[" << index << "].wire(*rt);\n";
        out << "  }\n";
      } else {
        out << "  flow->" << accessor << "()[" << index << "].wire(*rt);\n";
      }
    }
  }
  out << "  plan.finalize();\n";
  out << "}\n";
  return out.str();
}

}  // namespace tianshu::compiler
